function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(8)=(1+params(10))*(1+params(11));
    params(4)=params(12)/params(13)-params(11)-params(10)-params(10)*params(11);
    params(1)=(1+params(10))*(1+params(11))/(params(5)/params(13)+1-params(4));
    ys_(4)=0.33;
    ys_(3)=ys_(4)*(((1+params(11))*(1+params(10))*1/params(1)-(1-params(4)))/params(5))^(1/(params(5)-1));
    ys_(9)=ys_(3)*(params(10)*params(11)+params(4)+params(10)+params(11));
    ys_(1)=ys_(3)^params(5)*ys_(4)^(1-params(5));
    g=ys_(1)*params(9);
    params(14)=g;
    ys_(2)=ys_(4)^(1-params(5))*ys_(3)^params(5)*(1-params(9))-ys_(9);
    params(2)=(1-params(5))*(ys_(3)/ys_(4))^params(5)*(1-ys_(4))/ys_(2)^params(3);
    ys_(8)=(1-params(5))*ys_(1)/ys_(4);
    ys_(7)=ys_(1)*params(5)*4/ys_(3);
    ys_(10)=log(ys_(1));
    ys_(11)=log(ys_(3));
    ys_(12)=log(ys_(2));
    ys_(13)=log(ys_(4));
    ys_(14)=log(ys_(8));
    ys_(15)=log(ys_(9));
    ys_(5)=0;
    ys_(6)=0;
    % Auxiliary equations
end
