warning('off','all')
addpath C:/dynare/5.0/matlab
addpath C:/dynare/5.1/matlab
addpath C:/dynare/5.2/matlab
addpath C:/dynare/5.3/matlab
addpath C:/dynare/5.4/matlab
addpath C:/dynare/5.5/matlab
addpath C:/dynare/5.6/matlab
addpath C:/dynare/5.7/matlab
addpath C:/dynare/5.8/matlab
addpath C:/dynare/5.9/matlab
addpath C:/dynare/6.0/matlab
addpath C:/dynare/6.1/matlab
addpath C:/dynare/6.2/matlab
addpath C:/dynare/6.3/matlab
addpath C:/dynare/6.4/matlab
addpath C:/dynare/6.5/matlab
addpath C:/dynare/6.6/matlab
addpath C:/dynare/6.7/matlab
addpath C:/dynare/6.8/matlab
addpath C:/dynare/6.9/matlab
addpath C:/dynare/7.0/matlab
cd BKK
dynare BKK.mod
