%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'BKK';
M_.dynare_version = '4.6.1';
oo_.dynare_version = '4.6.1';
options_.dynare_version = '4.6.1';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('BKK.log');
M_.exo_names = cell(2,1);
M_.exo_names_tex = cell(2,1);
M_.exo_names_long = cell(2,1);
M_.exo_names(1) = {'E_H'};
M_.exo_names_tex(1) = {'E\_H'};
M_.exo_names_long(1) = {'E_H'};
M_.exo_names(2) = {'E_F'};
M_.exo_names_tex(2) = {'E\_F'};
M_.exo_names_long(2) = {'E_F'};
M_.endo_names = cell(42,1);
M_.endo_names_tex = cell(42,1);
M_.endo_names_long = cell(42,1);
M_.endo_names(1) = {'C_H'};
M_.endo_names_tex(1) = {'C\_H'};
M_.endo_names_long(1) = {'C_H'};
M_.endo_names(2) = {'L_H'};
M_.endo_names_tex(2) = {'L\_H'};
M_.endo_names_long(2) = {'L_H'};
M_.endo_names(3) = {'N_H'};
M_.endo_names_tex(3) = {'N\_H'};
M_.endo_names_long(3) = {'N_H'};
M_.endo_names(4) = {'A_H'};
M_.endo_names_tex(4) = {'A\_H'};
M_.endo_names_long(4) = {'A_H'};
M_.endo_names(5) = {'K_H'};
M_.endo_names_tex(5) = {'K\_H'};
M_.endo_names_long(5) = {'K_H'};
M_.endo_names(6) = {'Z_H'};
M_.endo_names_tex(6) = {'Z\_H'};
M_.endo_names_long(6) = {'Z_H'};
M_.endo_names(7) = {'X_H'};
M_.endo_names_tex(7) = {'X\_H'};
M_.endo_names_long(7) = {'X_H'};
M_.endo_names(8) = {'LAMBDA_H'};
M_.endo_names_tex(8) = {'LAMBDA\_H'};
M_.endo_names_long(8) = {'LAMBDA_H'};
M_.endo_names(9) = {'S_H'};
M_.endo_names_tex(9) = {'S\_H'};
M_.endo_names_long(9) = {'S_H'};
M_.endo_names(10) = {'NX_H'};
M_.endo_names_tex(10) = {'NX\_H'};
M_.endo_names_long(10) = {'NX_H'};
M_.endo_names(11) = {'Y_H'};
M_.endo_names_tex(11) = {'Y\_H'};
M_.endo_names_long(11) = {'Y_H'};
M_.endo_names(12) = {'C_F'};
M_.endo_names_tex(12) = {'C\_F'};
M_.endo_names_long(12) = {'C_F'};
M_.endo_names(13) = {'L_F'};
M_.endo_names_tex(13) = {'L\_F'};
M_.endo_names_long(13) = {'L_F'};
M_.endo_names(14) = {'N_F'};
M_.endo_names_tex(14) = {'N\_F'};
M_.endo_names_long(14) = {'N_F'};
M_.endo_names(15) = {'A_F'};
M_.endo_names_tex(15) = {'A\_F'};
M_.endo_names_long(15) = {'A_F'};
M_.endo_names(16) = {'K_F'};
M_.endo_names_tex(16) = {'K\_F'};
M_.endo_names_long(16) = {'K_F'};
M_.endo_names(17) = {'Z_F'};
M_.endo_names_tex(17) = {'Z\_F'};
M_.endo_names_long(17) = {'Z_F'};
M_.endo_names(18) = {'X_F'};
M_.endo_names_tex(18) = {'X\_F'};
M_.endo_names_long(18) = {'X_F'};
M_.endo_names(19) = {'LAMBDA_F'};
M_.endo_names_tex(19) = {'LAMBDA\_F'};
M_.endo_names_long(19) = {'LAMBDA_F'};
M_.endo_names(20) = {'S_F'};
M_.endo_names_tex(20) = {'S\_F'};
M_.endo_names_long(20) = {'S_F'};
M_.endo_names(21) = {'NX_F'};
M_.endo_names_tex(21) = {'NX\_F'};
M_.endo_names_long(21) = {'NX_F'};
M_.endo_names(22) = {'Y_F'};
M_.endo_names_tex(22) = {'Y\_F'};
M_.endo_names_long(22) = {'Y_F'};
M_.endo_names(23) = {'LGM'};
M_.endo_names_tex(23) = {'LGM'};
M_.endo_names_long(23) = {'LGM'};
M_.endo_names(24) = {'AUX_ENDO_LEAD_106'};
M_.endo_names_tex(24) = {'AUX\_ENDO\_LEAD\_106'};
M_.endo_names_long(24) = {'AUX_ENDO_LEAD_106'};
M_.endo_names(25) = {'AUX_ENDO_LEAD_111'};
M_.endo_names_tex(25) = {'AUX\_ENDO\_LEAD\_111'};
M_.endo_names_long(25) = {'AUX_ENDO_LEAD_111'};
M_.endo_names(26) = {'AUX_ENDO_LEAD_122'};
M_.endo_names_tex(26) = {'AUX\_ENDO\_LEAD\_122'};
M_.endo_names_long(26) = {'AUX_ENDO_LEAD_122'};
M_.endo_names(27) = {'AUX_ENDO_LEAD_376'};
M_.endo_names_tex(27) = {'AUX\_ENDO\_LEAD\_376'};
M_.endo_names_long(27) = {'AUX_ENDO_LEAD_376'};
M_.endo_names(28) = {'AUX_ENDO_LEAD_393'};
M_.endo_names_tex(28) = {'AUX\_ENDO\_LEAD\_393'};
M_.endo_names_long(28) = {'AUX_ENDO_LEAD_393'};
M_.endo_names(29) = {'AUX_ENDO_LEAD_139'};
M_.endo_names_tex(29) = {'AUX\_ENDO\_LEAD\_139'};
M_.endo_names_long(29) = {'AUX_ENDO_LEAD_139'};
M_.endo_names(30) = {'AUX_ENDO_LEAD_443'};
M_.endo_names_tex(30) = {'AUX\_ENDO\_LEAD\_443'};
M_.endo_names_long(30) = {'AUX_ENDO_LEAD_443'};
M_.endo_names(31) = {'AUX_ENDO_LEAD_460'};
M_.endo_names_tex(31) = {'AUX\_ENDO\_LEAD\_460'};
M_.endo_names_long(31) = {'AUX_ENDO_LEAD_460'};
M_.endo_names(32) = {'AUX_ENDO_LEAD_291'};
M_.endo_names_tex(32) = {'AUX\_ENDO\_LEAD\_291'};
M_.endo_names_long(32) = {'AUX_ENDO_LEAD_291'};
M_.endo_names(33) = {'AUX_ENDO_LAG_4_1'};
M_.endo_names_tex(33) = {'AUX\_ENDO\_LAG\_4\_1'};
M_.endo_names_long(33) = {'AUX_ENDO_LAG_4_1'};
M_.endo_names(34) = {'AUX_ENDO_LAG_4_2'};
M_.endo_names_tex(34) = {'AUX\_ENDO\_LAG\_4\_2'};
M_.endo_names_long(34) = {'AUX_ENDO_LAG_4_2'};
M_.endo_names(35) = {'AUX_ENDO_LAG_4_3'};
M_.endo_names_tex(35) = {'AUX\_ENDO\_LAG\_4\_3'};
M_.endo_names_long(35) = {'AUX_ENDO_LAG_4_3'};
M_.endo_names(36) = {'AUX_ENDO_LAG_8_1'};
M_.endo_names_tex(36) = {'AUX\_ENDO\_LAG\_8\_1'};
M_.endo_names_long(36) = {'AUX_ENDO_LAG_8_1'};
M_.endo_names(37) = {'AUX_ENDO_LAG_8_2'};
M_.endo_names_tex(37) = {'AUX\_ENDO\_LAG\_8\_2'};
M_.endo_names_long(37) = {'AUX_ENDO_LAG_8_2'};
M_.endo_names(38) = {'AUX_ENDO_LAG_28_1'};
M_.endo_names_tex(38) = {'AUX\_ENDO\_LAG\_28\_1'};
M_.endo_names_long(38) = {'AUX_ENDO_LAG_28_1'};
M_.endo_names(39) = {'AUX_ENDO_LAG_28_2'};
M_.endo_names_tex(39) = {'AUX\_ENDO\_LAG\_28\_2'};
M_.endo_names_long(39) = {'AUX_ENDO_LAG_28_2'};
M_.endo_names(40) = {'AUX_ENDO_LAG_28_3'};
M_.endo_names_tex(40) = {'AUX\_ENDO\_LAG\_28\_3'};
M_.endo_names_long(40) = {'AUX_ENDO_LAG_28_3'};
M_.endo_names(41) = {'AUX_ENDO_LAG_32_1'};
M_.endo_names_tex(41) = {'AUX\_ENDO\_LAG\_32\_1'};
M_.endo_names_long(41) = {'AUX_ENDO_LAG_32_1'};
M_.endo_names(42) = {'AUX_ENDO_LAG_32_2'};
M_.endo_names_tex(42) = {'AUX\_ENDO\_LAG\_32\_2'};
M_.endo_names_long(42) = {'AUX_ENDO_LAG_32_2'};
M_.endo_partitions = struct();
M_.param_names = cell(26,1);
M_.param_names_tex = cell(26,1);
M_.param_names_long = cell(26,1);
M_.param_names(1) = {'beta_H'};
M_.param_names_tex(1) = {'beta\_H'};
M_.param_names_long(1) = {'beta_H'};
M_.param_names(2) = {'alpha_H'};
M_.param_names_tex(2) = {'alpha\_H'};
M_.param_names_long(2) = {'alpha_H'};
M_.param_names(3) = {'eta_H'};
M_.param_names_tex(3) = {'eta\_H'};
M_.param_names_long(3) = {'eta_H'};
M_.param_names(4) = {'mu_H'};
M_.param_names_tex(4) = {'mu\_H'};
M_.param_names_long(4) = {'mu_H'};
M_.param_names(5) = {'gamma_H'};
M_.param_names_tex(5) = {'gamma\_H'};
M_.param_names_long(5) = {'gamma_H'};
M_.param_names(6) = {'theta_H'};
M_.param_names_tex(6) = {'theta\_H'};
M_.param_names_long(6) = {'theta_H'};
M_.param_names(7) = {'nu_H'};
M_.param_names_tex(7) = {'nu\_H'};
M_.param_names_long(7) = {'nu_H'};
M_.param_names(8) = {'sigma_H'};
M_.param_names_tex(8) = {'sigma\_H'};
M_.param_names_long(8) = {'sigma_H'};
M_.param_names(9) = {'delta_H'};
M_.param_names_tex(9) = {'delta\_H'};
M_.param_names_long(9) = {'delta_H'};
M_.param_names(10) = {'phi_H'};
M_.param_names_tex(10) = {'phi\_H'};
M_.param_names_long(10) = {'phi_H'};
M_.param_names(11) = {'psi_H'};
M_.param_names_tex(11) = {'psi\_H'};
M_.param_names_long(11) = {'psi_H'};
M_.param_names(12) = {'rho_H_H'};
M_.param_names_tex(12) = {'rho\_H\_H'};
M_.param_names_long(12) = {'rho_H_H'};
M_.param_names(13) = {'beta_F'};
M_.param_names_tex(13) = {'beta\_F'};
M_.param_names_long(13) = {'beta_F'};
M_.param_names(14) = {'alpha_F'};
M_.param_names_tex(14) = {'alpha\_F'};
M_.param_names_long(14) = {'alpha_F'};
M_.param_names(15) = {'eta_F'};
M_.param_names_tex(15) = {'eta\_F'};
M_.param_names_long(15) = {'eta_F'};
M_.param_names(16) = {'mu_F'};
M_.param_names_tex(16) = {'mu\_F'};
M_.param_names_long(16) = {'mu_F'};
M_.param_names(17) = {'gamma_F'};
M_.param_names_tex(17) = {'gamma\_F'};
M_.param_names_long(17) = {'gamma_F'};
M_.param_names(18) = {'theta_F'};
M_.param_names_tex(18) = {'theta\_F'};
M_.param_names_long(18) = {'theta_F'};
M_.param_names(19) = {'nu_F'};
M_.param_names_tex(19) = {'nu\_F'};
M_.param_names_long(19) = {'nu_F'};
M_.param_names(20) = {'sigma_F'};
M_.param_names_tex(20) = {'sigma\_F'};
M_.param_names_long(20) = {'sigma_F'};
M_.param_names(21) = {'delta_F'};
M_.param_names_tex(21) = {'delta\_F'};
M_.param_names_long(21) = {'delta_F'};
M_.param_names(22) = {'phi_F'};
M_.param_names_tex(22) = {'phi\_F'};
M_.param_names_long(22) = {'phi_F'};
M_.param_names(23) = {'psi_F'};
M_.param_names_tex(23) = {'psi\_F'};
M_.param_names_long(23) = {'psi_F'};
M_.param_names(24) = {'rho_F_F'};
M_.param_names_tex(24) = {'rho\_F\_F'};
M_.param_names_long(24) = {'rho_F_F'};
M_.param_names(25) = {'rho_H_F'};
M_.param_names_tex(25) = {'rho\_H\_F'};
M_.param_names_long(25) = {'rho_H_F'};
M_.param_names(26) = {'rho_F_H'};
M_.param_names_tex(26) = {'rho\_F\_H'};
M_.param_names_long(26) = {'rho_F_H'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 2;
M_.endo_nbr = 42;
M_.param_nbr = 26;
M_.orig_endo_nbr = 23;
M_.aux_vars(1).endo_index = 24;
M_.aux_vars(1).type = 0;
M_.aux_vars(1).orig_expr = 'LGM(1)';
M_.aux_vars(2).endo_index = 25;
M_.aux_vars(2).type = 0;
M_.aux_vars(2).orig_expr = 'AUX_ENDO_LEAD_106(1)';
M_.aux_vars(3).endo_index = 26;
M_.aux_vars(3).type = 0;
M_.aux_vars(3).orig_expr = 'AUX_ENDO_LEAD_111(1)';
M_.aux_vars(4).endo_index = 27;
M_.aux_vars(4).type = 0;
M_.aux_vars(4).orig_expr = 'Y_H(1)^(1+nu_H)*theta_H*LGM(1)*beta_H^4/K_H(-3)*(LAMBDA_H(1)*K_H(-3)^theta_H*N_H(1)^(1-theta_H))^(-nu_H)';
M_.aux_vars(5).endo_index = 28;
M_.aux_vars(5).type = 0;
M_.aux_vars(5).orig_expr = 'AUX_ENDO_LEAD_376(1)';
M_.aux_vars(6).endo_index = 29;
M_.aux_vars(6).type = 0;
M_.aux_vars(6).orig_expr = 'AUX_ENDO_LEAD_393(1)';
M_.aux_vars(7).endo_index = 30;
M_.aux_vars(7).type = 0;
M_.aux_vars(7).orig_expr = 'Y_F(1)^(1+nu_F)*theta_F*LGM(1)*beta_F^4/K_F(-3)*(LAMBDA_F(1)*K_F(-3)^theta_F*N_F(1)^(1-theta_F))^(-nu_F)';
M_.aux_vars(8).endo_index = 31;
M_.aux_vars(8).type = 0;
M_.aux_vars(8).orig_expr = 'AUX_ENDO_LEAD_443(1)';
M_.aux_vars(9).endo_index = 32;
M_.aux_vars(9).type = 0;
M_.aux_vars(9).orig_expr = 'AUX_ENDO_LEAD_460(1)';
M_.aux_vars(10).endo_index = 33;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 5;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(10).orig_expr = 'K_H(-1)';
M_.aux_vars(11).endo_index = 34;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 5;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(11).orig_expr = 'AUX_ENDO_LAG_4_1(-1)';
M_.aux_vars(12).endo_index = 35;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 5;
M_.aux_vars(12).orig_lead_lag = -3;
M_.aux_vars(12).orig_expr = 'AUX_ENDO_LAG_4_2(-1)';
M_.aux_vars(13).endo_index = 36;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 9;
M_.aux_vars(13).orig_lead_lag = -1;
M_.aux_vars(13).orig_expr = 'S_H(-1)';
M_.aux_vars(14).endo_index = 37;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 9;
M_.aux_vars(14).orig_lead_lag = -2;
M_.aux_vars(14).orig_expr = 'AUX_ENDO_LAG_8_1(-1)';
M_.aux_vars(15).endo_index = 38;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 16;
M_.aux_vars(15).orig_lead_lag = -1;
M_.aux_vars(15).orig_expr = 'K_F(-1)';
M_.aux_vars(16).endo_index = 39;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 16;
M_.aux_vars(16).orig_lead_lag = -2;
M_.aux_vars(16).orig_expr = 'AUX_ENDO_LAG_28_1(-1)';
M_.aux_vars(17).endo_index = 40;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 16;
M_.aux_vars(17).orig_lead_lag = -3;
M_.aux_vars(17).orig_expr = 'AUX_ENDO_LAG_28_2(-1)';
M_.aux_vars(18).endo_index = 41;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 20;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(18).orig_expr = 'S_F(-1)';
M_.aux_vars(19).endo_index = 42;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 20;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(19).orig_expr = 'AUX_ENDO_LAG_32_1(-1)';
M_.Sigma_e = zeros(2, 2);
M_.Correlation_matrix = eye(2, 2);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.linear_decomposition = false;
M_.orig_eq_nbr = 23;
M_.eq_nbr = 42;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 4;
M_.orig_maximum_endo_lead = 4;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 4;
M_.orig_maximum_lead = 4;
M_.orig_maximum_lag_with_diffs_expanded = 4;
M_.lead_lag_incidence = [
 0 21 0;
 0 22 0;
 0 23 63;
 1 24 0;
 2 25 0;
 3 26 0;
 0 27 0;
 4 28 64;
 5 29 0;
 0 30 0;
 0 31 65;
 0 32 0;
 0 33 0;
 0 34 66;
 6 35 0;
 7 36 0;
 8 37 0;
 0 38 0;
 9 39 67;
 10 40 0;
 0 41 0;
 0 42 68;
 0 43 69;
 0 44 70;
 0 45 71;
 0 46 72;
 0 47 73;
 0 48 74;
 0 49 75;
 0 50 76;
 0 51 77;
 0 52 78;
 11 53 0;
 12 54 0;
 13 55 0;
 14 56 0;
 15 57 0;
 16 58 0;
 17 59 0;
 18 60 0;
 19 61 0;
 20 62 0;]';
M_.nstatic = 8;
M_.nfwrd   = 14;
M_.npred   = 18;
M_.nboth   = 2;
M_.nsfwrd   = 16;
M_.nspred   = 20;
M_.ndynamic   = 34;
M_.dynamic_tmp_nbr = [46; 22; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'Y_H' ;
  2 , 'name' , 'K_H' ;
  3 , 'name' , 'X_H' ;
  4 , 'name' , 'A_H' ;
  5 , 'name' , 'L_H' ;
  6 , 'name' , '6' ;
  7 , 'name' , '7' ;
  8 , 'name' , '8' ;
  9 , 'name' , 'LGM' ;
  10 , 'name' , '10' ;
  11 , 'name' , 'NX_H' ;
  12 , 'name' , 'Y_F' ;
  13 , 'name' , 'K_F' ;
  14 , 'name' , 'X_F' ;
  15 , 'name' , 'A_F' ;
  16 , 'name' , 'L_F' ;
  17 , 'name' , '17' ;
  18 , 'name' , '18' ;
  19 , 'name' , '19' ;
  20 , 'name' , '20' ;
  21 , 'name' , '21' ;
  22 , 'name' , 'NX_F' ;
  23 , 'name' , '23' ;
};
M_.mapping.C_H.eqidx = [6 7 11 23 ];
M_.mapping.L_H.eqidx = [5 6 7 ];
M_.mapping.N_H.eqidx = [1 4 5 7 8 ];
M_.mapping.A_H.eqidx = [4 5 ];
M_.mapping.K_H.eqidx = [1 2 7 8 ];
M_.mapping.Z_H.eqidx = [1 9 11 23 ];
M_.mapping.X_H.eqidx = [3 11 23 ];
M_.mapping.LAMBDA_H.eqidx = [1 7 8 10 21 ];
M_.mapping.S_H.eqidx = [2 3 ];
M_.mapping.NX_H.eqidx = [11 ];
M_.mapping.Y_H.eqidx = [1 7 8 9 11 23 ];
M_.mapping.E_H.eqidx = [10 ];
M_.mapping.C_F.eqidx = [17 18 22 23 ];
M_.mapping.L_F.eqidx = [16 17 18 ];
M_.mapping.N_F.eqidx = [12 15 16 18 19 ];
M_.mapping.A_F.eqidx = [15 16 ];
M_.mapping.K_F.eqidx = [12 13 18 19 ];
M_.mapping.Z_F.eqidx = [12 20 22 23 ];
M_.mapping.X_F.eqidx = [14 22 23 ];
M_.mapping.LAMBDA_F.eqidx = [10 12 18 19 21 ];
M_.mapping.S_F.eqidx = [13 14 ];
M_.mapping.NX_F.eqidx = [22 ];
M_.mapping.Y_F.eqidx = [12 18 19 20 22 23 ];
M_.mapping.E_F.eqidx = [21 ];
M_.mapping.LGM.eqidx = [6 7 8 9 17 18 19 20 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [4 5 6 8 9 15 16 17 19 20 33 34 35 36 37 38 39 40 41 42 ];
M_.exo_names_orig_ord = [1:2];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(42, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(2, 1);
M_.params = NaN(26, 1);
M_.endo_trends = struct('deflator', cell(42, 1), 'log_deflator', cell(42, 1), 'growth_factor', cell(42, 1), 'log_growth_factor', cell(42, 1));
M_.NNZDerivatives = [154; -1; -1; ];
M_.static_tmp_nbr = [34; 24; 0; 0; ];
M_.params(1) = 0.99;
beta_H = M_.params(1);
M_.params(4) = 0.34;
mu_H = M_.params(4);
M_.params(5) = (-1.0);
gamma_H = M_.params(5);
M_.params(2) = 1;
alpha_H = M_.params(2);
M_.params(3) = 0.5;
eta_H = M_.params(3);
M_.params(6) = 0.36;
theta_H = M_.params(6);
M_.params(7) = 3;
nu_H = M_.params(7);
M_.params(8) = 0.01;
sigma_H = M_.params(8);
M_.params(9) = 0.025;
delta_H = M_.params(9);
M_.params(10) = 0.25;
phi_H = M_.params(10);
M_.params(11) = 0.5;
psi_H = M_.params(11);
M_.params(13) = 0.99;
beta_F = M_.params(13);
M_.params(16) = 0.34;
mu_F = M_.params(16);
M_.params(17) = (-1.0);
gamma_F = M_.params(17);
M_.params(14) = 1;
alpha_F = M_.params(14);
M_.params(15) = 0.5;
eta_F = M_.params(15);
M_.params(18) = 0.36;
theta_F = M_.params(18);
M_.params(19) = 3;
nu_F = M_.params(19);
M_.params(20) = 0.01;
sigma_F = M_.params(20);
M_.params(21) = 0.025;
delta_F = M_.params(21);
M_.params(22) = 0.25;
phi_F = M_.params(22);
M_.params(23) = 0.5;
psi_F = M_.params(23);
M_.params(12) = 0.906;
rho_H_H = M_.params(12);
M_.params(24) = 0.906;
rho_F_F = M_.params(24);
M_.params(25) = 0.088;
rho_H_F = M_.params(25);
M_.params(26) = 0.088;
rho_F_H = M_.params(26);
%
% INITVAL instructions
%
options_.initval_file = false;
oo_.steady_state(8) = 1;
oo_.steady_state(10) = 0;
oo_.steady_state(6) = 1;
oo_.steady_state(4) = 1;
oo_.steady_state(2) = 0.5;
oo_.steady_state(3) = 0.5;
oo_.steady_state(11) = 1;
oo_.steady_state(5) = 1;
oo_.steady_state(1) = 1;
oo_.steady_state(9) = 1;
oo_.steady_state(7) = 1;
oo_.exo_steady_state(1) = 0;
oo_.steady_state(19) = 1;
oo_.steady_state(21) = 0;
oo_.steady_state(17) = 1;
oo_.steady_state(15) = 1;
oo_.steady_state(13) = 0.5;
oo_.steady_state(14) = 0.5;
oo_.steady_state(22) = 1;
oo_.steady_state(16) = 1;
oo_.steady_state(12) = 1;
oo_.steady_state(20) = 1;
oo_.steady_state(18) = 1;
oo_.exo_steady_state(2) = 0;
oo_.steady_state(23) = 1;
oo_.steady_state(24)=oo_.steady_state(23);
oo_.steady_state(25)=oo_.steady_state(24);
oo_.steady_state(26)=oo_.steady_state(25);
oo_.steady_state(27)=oo_.steady_state(11)^(1+M_.params(7))*M_.params(6)*oo_.steady_state(23)*M_.params(1)^4/oo_.steady_state(5)*(oo_.steady_state(3)^(1-M_.params(6))*oo_.steady_state(8)*oo_.steady_state(5)^M_.params(6))^(-M_.params(7));
oo_.steady_state(28)=oo_.steady_state(27);
oo_.steady_state(29)=oo_.steady_state(28);
oo_.steady_state(30)=oo_.steady_state(22)^(1+M_.params(19))*M_.params(18)*oo_.steady_state(23)*M_.params(13)^4/oo_.steady_state(16)*(oo_.steady_state(14)^(1-M_.params(18))*oo_.steady_state(19)*oo_.steady_state(16)^M_.params(18))^(-M_.params(19));
oo_.steady_state(31)=oo_.steady_state(30);
oo_.steady_state(32)=oo_.steady_state(31);
oo_.steady_state(33)=oo_.steady_state(5);
oo_.steady_state(34)=oo_.steady_state(33);
oo_.steady_state(35)=oo_.steady_state(34);
oo_.steady_state(36)=oo_.steady_state(9);
oo_.steady_state(37)=oo_.steady_state(36);
oo_.steady_state(38)=oo_.steady_state(16);
oo_.steady_state(39)=oo_.steady_state(38);
oo_.steady_state(40)=oo_.steady_state(39);
oo_.steady_state(41)=oo_.steady_state(20);
oo_.steady_state(42)=oo_.steady_state(41);
if M_.exo_nbr > 0
	oo_.exo_simul = ones(M_.maximum_lag,1)*oo_.exo_steady_state';
end
if M_.exo_det_nbr > 0
	oo_.exo_det_simul = ones(M_.maximum_lag,1)*oo_.exo_det_steady_state';
end
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.00852)^2;
M_.Sigma_e(2, 2) = (0.00852)^2;
M_.Sigma_e(1, 2) = 0.258*sqrt(M_.Sigma_e(1, 1)*M_.Sigma_e(2, 2));
M_.Sigma_e(2, 1) = M_.Sigma_e(1, 2);
M_.Correlation_matrix(1, 2) = 0.258;
M_.Correlation_matrix(2, 1) = M_.Correlation_matrix(1, 2);
M_.sigma_e_is_diagonal = 0;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.hp_filter = 1600;
options_.order = 1;
options_.graph_format = {'pdf';'eps'};
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
save('BKK_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('BKK_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('BKK_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('BKK_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('BKK_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('BKK_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('BKK_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
